apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal-deployment
  namespace: pizzanow
spec:
   replicas: 1
   selector:
      matchLabels:
         app: paypal-service
   template:
      metadata:   
         labels:
            app: paypal-service
      spec:
         containers:
         -  name: paypal-docker-container
            image: hondocker23/paypal-service:2025-10-17-1319
            ports:
            - containerPort: 2025
            volumeMounts:
              - name: secret-volume
                mountPath: /etc/secret-pizzanow
                readOnly: true
              - name: config-volume
                mountPath: /etc/config-pizzanow
                readOnly: true
         volumes:
           - name: secret-volume
             secret:
               secretName: pizzanow-secret      
           - name: config-volume
             configMap:
               name: pizzanow-config
                