apiVersion: v1
kind: Service
metadata:
   name: paypal-endpoint
   namespace: pizzanow
spec:
   selector:
      app: paypal-service
   ports:
   - port: 4016
     targetPort: 2025
     nodePort: 30003
   type: NodePort