apiVersion: v1
kind: Service
metadata:
   name: paypal-endpoint
   namespace: pizzanow
spec:
   selector:
      app: paypal-service
   ports:
   - port: 80
     targetPort: 2025     
   type: ClusterIP