apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  namespace: pizzanow
spec:
   replicas: 1
   selector:
      matchLabels:
         app: bot-service
   template:
      metadata:   
         labels:
            app: bot-service
      spec:
         containers:
         -  name: bot-docker-container
            image: hondocker23/bot-service:2025-10-19-2246
            ports:
            - containerPort: 2025
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret-pizzanow/vertex.json
            volumeMounts:
              - name: secret-volume
                mountPath: /etc/secret-pizzanow
                readOnly: true
              - name: config-volume
                mountPath: /etc/config-pizzanow
                readOnly: true
         volumes:
           - name: secret-volume
             secret:
               secretName: pizzanow-secret    
           - name: config-volume  
             configMap:
               name: pizzanow-config
                