apiVersion: v1
kind: Service
metadata:
   name: bot-endpoint
   namespace: pizzanow
spec:
   selector:
      app: bot-service
   ports:
   - port: 4016
     targetPort: 2025
     nodePort: 30002
   type: NodePort