# 1. kubectl create secret generic vertex-secret-meta \
#   --from-file=vertex.json=backend/core/vertex.json \
#   -n pizzanow

# 2. Inside bot/deployment.yaml
# spec:
#       containers:
#       - name: bot-container
#         image: bot-service:latest
#         ports:
#         - containerPort: 2025
#         volumeMounts:
#         - name: vertex-secret
#           mountPath: /app/vertex.json
#           subPath: vertex.json
#       volumes:
#       - name: vertex-secret
#         secret:
#           secretName: vertex-secret-meta

