apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: pizzanow
spec:
   replicas: 1
   selector:
      matchLabels:
         app: auth-service
   template:
      metadata:   
         labels:
            app: auth-service
      spec:
         containers:
         -  name: auth-docker-container
            image: hondocker23/auth-service:2025-10-20-0013 
            ports:
            - containerPort: 2025                      
            volumeMounts:
              - name: secret-volume
                mountPath: /etc/secret-pizzanow
                readOnly: true
              - name: config-volume
                mountPath: /etc/config-pizzanow
                readOnly: true
         volumes:
           - name: secret-volume
             secret:
               secretName: pizzanow-secret     
           - name: config-volume
             configMap:
               name: pizzanow-config   
                