apiVersion: v1
kind: Service
metadata:
   name: auth-endpoint
   namespace: pizzanow
spec:
   selector:
      app: auth-service
   ports:
   - port: 4016
     targetPort: 2025
     nodePort: 30000
   type: NodePort