apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pizzanow-ingress
  namespace: pizzanow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: pizzanow.local.com
    http:
      paths:
      # --- frontend ---
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fe-endpoint
            port:
              number: 80

      # --- auth-endpoint ---
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-endpoint
            port:
              number: 4016

      # --- bot-endpoint ---
      - path: /api/pizzas
        pathType: Prefix
        backend:
          service:
            name: bot-endpoint
            port:
              number: 4017
      - path: /api/query
        pathType: Prefix
        backend:
          service:
            name: bot-endpoint
            port:
              number: 4017

      # --- profile-endpoint ---
      - path: /api/profile
        pathType: Prefix
        backend:
          service:
            name: profile-endpoint
            port:
              number: 4018

      # --- paypal-endpoint ---
      - path: /api/paypal
        pathType: Prefix
        backend:
          service:
            name: paypal-endpoint
            port:
              number: 4019
