apiVersion: v1
kind: Pod
metadata:
  name: test-auth
  namespace: pizzanow
spec:
  containers:
  - name: test-auth
    image: hondocker23/auth-service:2025-10-16-2148
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/config
        readOnly: true
    command: ["sleep", "3600"]
  volumes:
    - name: secret-volume
      secret:
        secretName: pizzanow-secret
