apiVersion: v1
kind: Secret
metadata:
   name: pizzanow-proj-secret
data:
   ENV: UFJPRA==
   DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL25lb25kYl9vd25lcjpucGdfbjY1SW9EcVpVa1FUQGVwLWRlbGljYXRlLWJhbmQtYTRrOGIwZGQudXMtZWFzdC0xLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbG1vZGU9cmVxdWlyZQ==
   PROJECT_ID: cGl6emFub3dhaQ==
   VERTEX_REGION: dXMtY2VudHJhbDE=
   ALLOWED_ORIGINS: http://localhost:5173,http://localhost:4173,https://pizza-now-ai.vercel.app/
   SECRET_KEY: YWJjMTIzeHl6Nzg5d293U3VjaFNlY3JldEBAQGRvbnRHdWVzc1RoaXNQbHM=
   ALGORITHM: SFMyNTY=
   ACCESS_TOKEN_EXPIRE_MINUTES: NDMyMDA=

   AWS_ACCESS_KEY_ID: QUtJQVk0SVpNNkNCNVA1UlQ2V0Y=
   AWS_SECRET_ACCESS_KEY: VWpXQlcwRDVCSXp4QzJpd3J1cXhrMkJ4ZDA3MEt6Mm5BTVVSaG0rUQ==
   AWS_REGION: dXMtZWFzdC0x
   AWS_S3_BUCKET: cGl6emFub3dpbWFnZXM=