apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: pizzanow
spec:
   replicas: 1
   selector:
      matchLabels:
         app: fe-service
   template:
      metadata:   
         labels:
            app: fe-service
      spec:
         containers:
         - name: fe-docker-container
           image: hondocker23/fe-service:2025-10-17-1440
           ports:
           - containerPort: 80
           
           
   
