apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  namespace: pizzanow
spec:
   replicas: 1
   selector:
      matchLabels:
         app: profile-service
   template:
      metadata:   
         labels:
            app: profile-service
      spec:
         containers:
         -  name: profile-docker-container
            image: hondocker23/profile-service:2025-10-08-1511
            ports:
            - containerPort: 2025
            envFrom:
            - configMapRef:
                name: pizzanow-config
            volumeMounts:
              - name: secret-volume
                mountPath: /etc/config
                readOnly: true
         volumes:
           - name: secret-volume
             secret:
               secretName: pizzanow-secret
            