apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  namespace: pizzanow
spec:
   replicas: 1
   selector:
      matchLabels:
         app: profile-service
   template:
      metadata:   
         labels:
            app: profile-service
      spec:
         containers:
         -  name: profile-docker-container
            image: hondocker23/profile-service:2025-10-19-2250
            ports:
            - containerPort: 2025           
            volumeMounts:
              - name: secret-volume
                mountPath: /etc/secret-pizzanow
                readOnly: true
              - name: config-volume
                mountPath: /etc/config-pizzanow
                readOnly: true
         volumes:
           - name: secret-volume
             secret:
               secretName: pizzanow-secret
           - name: config-volume
             configMap:
               name: pizzanow-config
            