apiVersion: v1
kind: Service
metadata:
   name: profile-endpoint
   namespace: pizzanow
spec:
   selector:
      app: profile-service
   ports:
   - port: 4016
     targetPort: 2025
     nodePort: 30001
   type: NodePort