apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
   replicas: 1
   selector:
      matchLabels:
         app: fe-service
   template:
      metadata:   
         labels:
            app: fe-service
      spec:
         containers:
         - name: fe-docker-container
           image: hondocker23/fe-service:2025-09-18-1710
           ports:
           - containerPort: 4444
           env:
            - name: AUTH_API_URL
              value: "http://auth-service:8081"
            - name: PROFILE_API_URL
              value: "http://profile-service:8082"